//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCAL.Base.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GCAL.Base.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3039163	Sant Julià de Lòria	Sant Julia de Loria	San Julia,San Julià,Sant Julia de Loria,Sant Julià de Lòria,Sant-Zhulija-de-Lorija,sheng hu li ya-de luo li ya,Сант-Жулия-де-Лория,サン・ジュリア・デ・ロリア教区,圣胡利娅-德洛里亚,圣胡利娅－德洛里亚	42.46372	1.49129	P	PPLA	AD		06				8022		921	Europe/Andorra	2013-11-23
        ///3039678	Ordino	Ordino	Ordino,ao er di nuo,orudino jiao qu,Ордино,オルディノ教区,奥尔迪诺	42.55623	1.53319	P	PPLA	AD		05				3066		1296	Europe/Andorra	2009-12-11
        ///3040051	les Escaldes	les Escaldes	Ehskal&apos;des-Ehndzhordani,Escaldes,Escaldes-En [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cities2016 {
            get {
                return ResourceManager.GetString("cities2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ISO	ISO3	fips	Country	Capital	Area(in sq km)	Population	Continent	neighbours
        ///AD	AND	AN	Andorra	Andorra la Vella	468	84000	EU	ES,FR
        ///AE	ARE	AE	United Arab Emirates	Abu Dhabi	82880	4975593	AS	SA,OM
        ///AF	AFG	AF	Afghanistan	Kabul	647500	29121286	AS	TM,CN,IR,TJ,PK,UZ
        ///AG	ATG	AC	Antigua and Barbuda	St. John&apos;s	443	86754	NA	
        ///AI	AIA	AV	Anguilla	The Valley	102	13254	NA	
        ///AL	ALB	AL	Albania	Tirana	28748	2986952	EU	MK,GR,ME,RS,XK
        ///AM	ARM	AM	Armenia	Yerevan	29800	2968000	AS	GE,IR,AZ,TR
        ///AO	AGO	AO	Angola	Luanda	1246700	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string countries2016 {
            get {
                return ResourceManager.GetString("countries2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] events {
            get {
                object obj = ResourceManager.GetObject("events", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] strings {
            get {
                object obj = ResourceManager.GetObject("strings", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined	0	0	0	0	0	0	0	0	0	0	
        ///UTC-12	-720	0	0	0	0	0	0	0	0	0	
        ///Pacific/Apia	780	60	0	4	1	0	0	9	5	0	WS
        ///Pacific/Midway	-660	0	0	0	0	0	0	0	0	0	UM
        ///Pacific/Niue	-660	0	0	0	0	0	0	0	0	0	NU
        ///Pacific/Pago_Pago	-660	0	0	0	0	0	0	0	0	0	AS
        ///UTC-11	-660	0	0	0	0	0	0	0	0	0	
        ///America/Adak	-600	60	0	3	2	0	0	11	1	0	US
        ///Pacific/Fakaofo	780	0	0	0	0	0	0	0	0	0	TK
        ///Pacific/Honolulu	-600	0	0	0	0	0	0	0	0	0	US
        ///Pacific/Johnston	-600	0	0	0	0	0	0	0	0	0	UM
        ///Pacific/Rarotonga	-600	0	0	0	0	0	0	0	0	0	CK
        ///Pacific/Tahiti	-600	0	0	0	0	0	0	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string timezones2016 {
            get {
                return ResourceManager.GetString("timezones2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountryCode	TimeZoneId	GMT offset 1. Jan 2016	DST offset 1. Jul 2016	rawOffset (independant of DST)
        ///CI	Africa/Abidjan	0.0	0.0	0.0
        ///GH	Africa/Accra	0.0	0.0	0.0
        ///ET	Africa/Addis_Ababa	3.0	3.0	3.0
        ///DZ	Africa/Algiers	1.0	1.0	1.0
        ///ER	Africa/Asmara	3.0	3.0	3.0
        ///ML	Africa/Bamako	0.0	0.0	0.0
        ///CF	Africa/Bangui	1.0	1.0	1.0
        ///GM	Africa/Banjul	0.0	0.0	0.0
        ///GW	Africa/Bissau	0.0	0.0	0.0
        ///MW	Africa/Blantyre	2.0	2.0	2.0
        ///CG	Africa/Brazzaville	1.0	1.0	1.0
        ///BI	Africa/Bujumbura	2.0	2.0	2.0
        ///EG	Africa/Cairo	2.0	2.0	2.0
        ///MA	Africa/Casablanca [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string timezoneUpdates {
            get {
                return ResourceManager.GetString("timezoneUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To calculate a full calendar for any location, press F8, or choose Calendar from the Calculate menu.
        ///Whenever you start GCal it will first show you today&apos;s events for the default location. Be sure to tell GCal where you are in the world - choose My Location from the Settings menu.
        ///You can quickly see the events coming up in the next few days at your location. From the Today screen, press F7. To move to the day before, press F5. To return to the current day, press F6.
        ///Screen output formatting can be custo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tips {
            get {
                return ResourceManager.GetString("tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group;Name;Value
        ///# (set group &quot;default&quot;)
        ///# (foreach ab : appday.items
        ///#     (if (x app canDisplay ab.DsCondition)) then
        ///#         (if ab.isInfo then
        ///[group];[ab.Name];[ab.Value]
        ///#         )
        ///#         (if ab.isSeparator then
        ///#             (set group ab.Name)
        ///#         )
        ///#     )
        ///# ).
        /// </summary>
        internal static string TplAppDayCsv {
            get {
                return ResourceManager.GetString("TplAppDayCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;&lt;title&gt;Appearance day&lt;/title&gt;
        ///&lt;style&gt;
        ///&lt;!--
        ///body {
        ///  font-family:Verdana;
        ///  font-size:11pt;
        ///}
        ///
        ///td.hed {
        ///  font-size:11pt;
        ///  font-weight:bold;
        ///
        ///  background:#aaaaaa;
        ///  color:white;
        ///  text-align:center;
        ///  vertical-align:center;
        ///  padding-left:15pt;
        ///  padding-right:15pt;
        ///
        ///  padding-top:5pt;
        ///  padding-bottom:5pt;
        ///}
        ///--&gt;
        ///&lt;/style&gt;
        ///
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///&lt;h2 align=center&gt;Appearance day Calculation&lt;/h2&gt;
        ///&lt;table align=center&gt;&lt;tr&gt;&lt;td valign=top&gt;
        ///
        ///
        ///&lt;table align=center&gt;
        ///
        ///
        ///# (foreach ab : appday.items
        ///#   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TplAppDayHtml {
            get {
                return ResourceManager.GetString("TplAppDayHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance Day
        ///
        ///# (foreach ab : appday.items
        ///#     (if (x app canDisplay ab.DsCondition)) then
        ///#         (if ab.isInfo then
        ///    [ab.Name:-15s] : [ab.Value]
        ///#         )
        ///#         (if ab.isSeparator then
        ///
        ///  [ab.Name]
        ///#         )
        ///#     )
        ///# )
        ///
        ///-------------------------------------------------------------------------------
        ///Notes:
        ///
        ///DST - Time is in &apos;Daylight Saving Time&apos;
        ///LT  - Time is in &apos;Local Time&apos;
        ///
        ///Generated by [app.versionName].
        /// </summary>
        internal static string TplAppDayPlain {
            get {
                return ResourceManager.GetString("TplAppDayPlain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## TEMPLATE for RTF format
        ///## APP DAY screen
        ///##
        ///{\rtf1\ansi\ansicpg1252\deff2\deflang1033{\fonttbl{\f0\fswiss\fcharset0 Lucida Console;}
        ///{\f1\fswiss\fcharset0 Arial;}{\f2\froman\fprq2\fcharset0 Book Antiqua;}}
        ///{\colortbl ;\red0\green0\blue0;\red16\green16\blue16;\red32\green32\blue32;\red48\green48\blue48;\red64\green64\blue64;
        ///\red80\green80\blue80;\red96\green96\blue96;\red112\green112\blue112;\red128\green128\blue128;\red143\green143\blue143;
        ///\red159\green159\blue159;\red175\green175\blue175;\red1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TplAppDayRtf {
            get {
                return ResourceManager.GetString("TplAppDayRtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xml&gt;
        ///	&lt;body type=&quot;Appearance Day&quot;&gt;
        ///# (set group &quot;default&quot;)
        ///# (foreach ab : appday.items
        ///#     (if (x app canDisplay ab.DsCondition)) then
        ///#         (if ab.isInfo then
        ///		&lt;item group=&quot;[group]&quot; name=&quot;[ab.Name]&quot;&gt;[ab.Value]&lt;/item&gt;
        ///#         )
        ///#         (if ab.isSeparator then
        ///#             (set group ab.Name)
        ///#         )
        ///#     )
        ///# )
        ///		&lt;generator&gt;[app.versionName]&lt;/generator&gt;
        ///	&lt;/body&gt;
        ///&lt;/xml&gt;.
        /// </summary>
        internal static string TplAppDayXml {
            get {
                return ResourceManager.GetString("TplAppDayXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Subject&quot;,&quot;Begin Date&quot;,&quot;Start&quot;,&quot;End Date&quot;,&quot;End&quot;,&quot;WholeDay&quot;,&quot;Alarm&quot;
        ///# (set lastmasa -1)
        ///# (foreach k : calendar.itemIndexes
        ///#     (set prevd (x calendar getDay (- k 1)))
        ///#     (set pvd   (x calendar getDay k)) 
        ///#     (set nextd (x calendar getDay (+ k 1)))
        ///#     (if (!= pvd.astro.nMasa lastmasa) then
        ///#         (set lastmasa pvd.astro.nMasa)
        ///#     )
        ///#     (if (or (== (x app getDispValue 20) 0) (&gt; pvd.events.count 0)) then
        ///#         (print &quot;\&quot;&quot;);
        ///#         (print pvd.tithiNameExt)
        ///#         (print  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TplCalendarCsv {
            get {
                return ResourceManager.GetString("TplCalendarCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # (set lastmonth -1)
        ///# (set lastmasa -1)
        ///#     (if (or (== (x app getDispValue 20) 0) (&gt; pvd.visibleEvents.count 0)) then
        ///#         (if (&lt; pvd.astro.sunLongitude 0.0) then
        ///             No sunrise and no sunset for this day
        ///#         else
        ///#             (print &quot; [pvd.date.shortDate:-11s] [pvd.date.dayOfWeekAbbr:3s] [pvd.tithiNameExt:32s] &quot;)
        ///#             (if (x app getDispValue 39) then (print &quot;[pvd.astro.paksaAbbr] &quot;))
        ///#             (if (x app getDispValue 37) then (print &quot;[pvd.astro.yogaName:10s] &quot;) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TplCalendarDayPlain {
            get {
                return ResourceManager.GetString("TplCalendarDayPlain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;title&gt;Calendar [calendar.startDate.year]&lt;/title&gt;
        ///&lt;style&gt;
        ///&lt;!--
        ///body {
        ///  font-family:Verdana;
        ///  font-size:11pt;
        ///}
        ///td.hed {
        ///  font-family:Verdana;
        ///  font-size:9pt;
        ///  font-weight:bold;
        ///  background:#aaaaaa;
        ///  color:white;
        ///  text-align:center;
        ///  vertical-align:center;
        ///  padding-left:15pt;
        ///  padding-right:15pt;
        ///  padding-top:5pt;
        ///  padding-bottom:5pt;
        ///}
        ///--&gt;
        ///&lt;/style&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///# (set lastmonth -1)
        ///# (set lastmasa -1)
        ///# (foreach i : calendar.itemIndexe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TplCalendarHtml {
            get {
                return ResourceManager.GetString("TplCalendarHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;title&gt;Calendar [calendar.startDate.year]&lt;/title&gt;
        ///&lt;style&gt;
        ///&lt;!--
        ///body {
        ///  font-family:Verdana;
        ///  font-size:11pt;
        ///}
        ///td.hed {
        ///  font-family:Verdana;
        ///  font-size:9pt;
        ///  font-weight:bold;
        ///  background:#aaaaaa;
        ///  color:white;
        ///  text-align:center;
        ///  vertical-align:center;
        ///  padding-left:15pt;
        ///  padding-right:15pt;
        ///  padding-top:5pt;
        ///  padding-bottom:5pt;
        ///}
        ///--&gt;
        ///&lt;/style&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///# (set lastmonth -1)
        ///# (set lastmasa -1)
        ///# (foreach i : calendar.itemIndexe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TplCalendarHtmlComplete {
            get {
                return ResourceManager.GetString("TplCalendarHtmlComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # (set g_firstday_in_week (x app getDispValue GCDS.GENERAL_FIRST_DOW))
        ///# (set k 0)
        ///# (set y 0)
        ///# (set lwd 0)
        ///# (set nPrevMasa -1)
        ///# (set prevMas -1)
        ///# (set brw 0)
        ///
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;Calendar [calendar.startDate]&lt;/title&gt;
        ///
        ///&lt;style&gt;
        ///&lt;!--
        ///p.MsoNormal, li.MsoNormal, div.MsoNormal
        ///{
        ///	mso-style-parent:\&quot;\&quot;;
        ///	margin:0in;margin-bottom:.0001pt;
        ///	mso-pagination:widow-orphan;
        ///	font-size:8.0pt;
        ///	font-family:Arial;
        ///	mso-fareast-font-family:Arial;
        ///}
        ///
        ///p.month
        ///{
        ///	mso-style-name:month;
        ///	mso-margin-top [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TplCalendarHtmlTable {
            get {
                return ResourceManager.GetString("TplCalendarHtmlTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # (set k 0)
        ///# (set lastmasa -1)
        ///# (set st (x app new &apos;DateTime))
        ///BEGIN:VCALENDAR
        ///VERSION:2.0
        ///X-WR-CALNAME:VAISNAVA
        ///PRODID:-//GBC Calendar Comitee//GCAL//EN
        ///X-WR-RELCALID:[st.millisecond:08d]-[st.dayOfWeek:04d]-[st.Month:04d]-[st.Hour:04d]-[st.Minute:04d][st.millisecond:08d]
        ///X-WR-TIMEZONE:[location.timeZoneName]
        ///CALSCALE:GREGORIAN
        ///METHOD:PUBLISH
        ///BEGIN:VTIMEZONE
        ///TZID:[location.timeZoneName]
        ///LAST-MODIFIED:[st.standardDateString]T[st.standardTimeString]dZ
        ///# (set tzoffset (x app getTimezoneOffset l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TplCalendarICAL {
            get {
                return ResourceManager.GetString("TplCalendarICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # (set lastmonth -1)
        ///# (set lastmasa -1)
        ///# (foreach i : calendar.itemIndexes
        ///#     (set pvd (x calendar getDay i))
        ///#     (set nMasaHeader 0)
        ///#     (if (and (eq (x app calendarHeaderType) 0) (!= pvd.astro.masa lastmasa)) then
        ///
        ///
        ///                   [pvd.astro.masaName:-20s] Masa, Gaurabda [pvd.astro.gaurabdaYear:6s]         [app.versionShort:-10s]
        ///#         (if (and (eq pvd.astro.masa 12) (&gt;= lastmasa 3) (&lt;= lastmasa 6)) then
        ///                (Caturmasya is not observed during Purusottama Adhika Masa. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TplCalendarPlain {
            get {
                return ResourceManager.GetString("TplCalendarPlain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## TEMPLATE for RTF format
        ///## CALENDAR
        ///##
        ///{\rtf1\ansi\ansicpg1252\deff2\deflang1033{\fonttbl{\f0\fswiss\fcharset0 Lucida Console;}
        ///{\f1\fswiss\fcharset0 Arial;}{\f2\froman\fprq2\fcharset0 Book Antiqua;}}
        ///{\colortbl ;\red0\green0\blue0;\red16\green16\blue16;\red32\green32\blue32;\red48\green48\blue48;\red64\green64\blue64;
        ///\red80\green80\blue80;\red96\green96\blue96;\red112\green112\blue112;\red128\green128\blue128;\red143\green143\blue143;
        ///\red159\green159\blue159;\red175\green175\blue175;\red191\gre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TplCalendarRtf {
            get {
                return ResourceManager.GetString("TplCalendarRtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;title&gt;Calendar [calendar.startDate.year]&lt;/title&gt;
        ///&lt;style&gt;
        ///&lt;!--
        ///body {
        ///  font-family:Arial;
        ///  font-size:9pt;
        ///}
        ///td {
        ///  font-family:Arial;
        ///  font-size:9pt;
        ///}
        ///td.hed {
        ///  font-family:Arial;
        ///  font-size:9pt;
        ///  font-weight:bold;
        ///  background:#aaaaaa;
        ///  color:white;
        ///  text-align:center;
        ///  vertical-align:center;
        ///  padding-left:5pt;
        ///  padding-right:5pt;
        ///  padding-top:5pt;
        ///  padding-bottom:5pt;
        ///}
        ///--&gt;
        ///&lt;/style&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///# (set lastmonth -1)
        ///# (set lastma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TplCalendarSadhana {
            get {
                return ResourceManager.GetString("TplCalendarSadhana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # (set k 0)
        ///# (set lastmasa -1)
        ///# (set st (x app new &apos;DateTime))
        ///#
        ///BEGIN:VCALENDAR
        ///VERSION:1.0
        ///X-WR-CALNAME:VAISNAVA
        ///PRODID:-//GBC Calendar Comitee//GCAL//EN
        ///X-WR-RELCALID:[st.millisecond:08d]-[st.dayOfWeek:04d]-[st.Month:04d]-[st.Hour:04d]-[st.Minute:04d][st.millisecond:08d]
        ///X-WR-TIMEZONE:[location.timeZoneName]
        ///CALSCALE:GREGORIAN
        ///METHOD:PUBLISH
        ///#
        ///# (foreach k : calendar.itemIndexes
        ///#     (set pvd (x calendar getDay k))
        ///#     (if (&gt;= pvd.astro.sunLongitude 0.0) then
        ///#         (if pvd.ekadas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TplCalendarVCAL {
            get {
                return ResourceManager.GetString("TplCalendarVCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xml&gt; 
        /// &lt;request name=&quot;Calendar&quot; version=&quot;[app.versionShort]&quot;&gt; 
        ///  &lt;arg name=&quot;longitude&quot; val=&quot;[location.longitude]&quot; /&gt;
        ///  &lt;arg name=&quot;latitude&quot; val=&quot;[location.latitude]&quot; /&gt;
        ///  &lt;arg name=&quot;timezone&quot; val=&quot;[location.timeZoneName]&quot; /&gt;
        ///  &lt;arg name=&quot;startdate&quot; val=&quot;[calendar.startDate]&quot; /&gt;
        /// &lt;/request&gt; 
        /// &lt;result name=&quot;Calendar&quot;&gt;
        ///  &lt;dstsystem name=&quot;[location.timeZoneName]&quot; /&gt;
        ///
        ///# (foreach k : calendar.itemIndexes
        ///#     (set pvd (x calendar getDay k))
        ///#     (if (!= nPrevMasa pvd.astro.nMasa) then
        ///#         (i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TplCalendarXml {
            get {
                return ResourceManager.GetString("TplCalendarXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date;Time;DST;EventText;Location
        ///# (foreach dnr : events.items
        ///[dnr.Time.shortDate];[dnr.Time.longTime];[dnr.dstSignature];[dnr.typeString];[location.fullName]
        ///# ).
        /// </summary>
        internal static string TplCoreEventsCsv {
            get {
                return ResourceManager.GetString("TplCoreEventsCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;Core Events&lt;/title&gt;
        ///&lt;style&gt;
        ///&lt;!--
        ///body {
        ///  font-family:Verdana;
        ///  font-size:11pt;
        ///}
        ///
        ///td.hed {
        ///  font-size:11pt;
        ///  font-weight:bold;
        ///
        ///  background:#aaaaaa;
        ///  color:white;
        ///  text-align:center;
        ///  vertical-align:center;
        ///  padding-left:15pt;
        ///  padding-right:15pt;
        ///
        ///  padding-top:5pt;
        ///  padding-bottom:5pt;
        ///}
        ///--&gt;
        ///&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///&lt;p style=&apos;text-align:center&apos;&gt;&lt;span style=&apos;font-size:14pt&apos;&gt;Core Events&lt;/span&gt;
        ///&lt;/br&gt;Location: [location.fullName]&lt;/p&gt;
        ///&lt;p align=cent [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TplCoreEventsHtml {
            get {
                return ResourceManager.GetString("TplCoreEventsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Events
        ///From [events.startDate.shortDate] to [events.endDate.shortDate]
        ///Location: [location.fullName]
        ///
        ///
        ///# (set prevd (x app new &apos;GregorianDateTime))
        ///# (set prevt -1)
        ///# (x prevd setDay 0)
        ///# (x prevd setMonth 0)
        ///# (x prevd setYear 0)
        ///# (foreach dnr : events.items
        ///#     (if events.isSortedByTime then
        ///#         (if (or (!= prevd.day dnr.Time.day) (!= prevd.month dnr.Time.month) (!= prevd.year dnr.Time.year)) then
        ///
        /// ===========  [dnr.Time.shortDate] - [dnr.Time.dayOfWeekName] ================== [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TplCoreEventsPlain {
            get {
                return ResourceManager.GetString("TplCoreEventsPlain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff2\deflang1033{\fonttbl{\f0\fswiss\fcharset0 Lucida Console;}
        ///{\f1\fswiss\fcharset0 Arial;}{\f2\froman\fprq2\fcharset0 Book Antiqua;}}
        ///{\colortbl ;\red0\green0\blue0;\red16\green16\blue16;\red32\green32\blue32;\red48\green48\blue48;\red64\green64\blue64;
        ///\red80\green80\blue80;\red96\green96\blue96;\red112\green112\blue112;\red128\green128\blue128;\red143\green143\blue143;
        ///\red159\green159\blue159;\red175\green175\blue175;\red191\green191\blue191;\red207\green207\blue207;\red22 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TplCoreEventsRtf {
            get {
                return ResourceManager.GetString("TplCoreEventsRtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xml&gt;
        ///	&lt;body name=&quot;Core Events&quot;&gt;
        ///		&lt;generator&gt;Generated by [app.versionName]&lt;/generator&gt;
        ///		&lt;location&gt;[location.fullName]&lt;/location&gt;
        ///
        ///# (foreach dnr : events.items
        ///		&lt;event&gt;
        ///			&lt;date&gt;[dnr.Time.shortDate]&lt;/date&gt;
        ///			&lt;time dst=&quot;[dnr.dstSignature]&quot;&gt;[dnr.Time.longTime]&lt;/time&gt;
        ///			&lt;eventText&gt;[dnr.typeString]&lt;/eventText&gt;
        ///		&lt;/event&gt;
        ///# )
        ///
        ///	&lt;/body&gt;
        ///&lt;/xml&gt;
        ///.
        /// </summary>
        internal static string TplCoreEventsXml {
            get {
                return ResourceManager.GetString("TplCoreEventsXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year;Masa;StartDate;EndDate;Location
        ///# (foreach item : mlist.items
        ///[item.year];[item.masaName];[item.startDate.shortDate];[item.endDate.shortDate];[location.fullName]
        ///# ).
        /// </summary>
        internal static string TplMasaListCsv {
            get {
                return ResourceManager.GetString("TplMasaListCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;Masa List&lt;/title&gt;
        ///&lt;style&gt;
        ///&lt;!--
        ///body {
        ///  font-family:Verdana;
        ///  font-size:11pt;
        ///}
        ///
        ///td.hed {
        ///  font-size:11pt;
        ///  font-weight:bold;
        ///
        ///  background:#aaaaaa;
        ///  color:white;
        ///  text-align:center;
        ///  vertical-align:center;
        ///  padding-left:15pt;
        ///  padding-right:15pt;
        ///
        ///  padding-top:5pt;
        ///  padding-bottom:5pt;
        ///}
        ///--&gt;
        ///&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///&lt;p style=&apos;text-align:center&apos;&gt;&lt;span style=&apos;font-size:14pt&apos;&gt;Masa List&lt;/span&gt;
        ///&lt;/br&gt;Location: [location.fullName]&lt;/p&gt;
        ///&lt;p align=center&gt;F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TplMasaListHtml {
            get {
                return ResourceManager.GetString("TplMasaListHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Masa Listing
        /// 
        /// Location: [location.fullName]
        /// From [mlist.startDate.shortDate] to [mlist.endDate.shortDate]
        /// ==================================================================
        ///
        ///# (foreach item : mlist.items
        ///#    (set my (+ item.masaName &quot; &quot; item.year))
        ///#    (set sy (+ item.startDate.shortDate &quot; - &quot;))
        ///#    (set ey item.endDate.shortDate)
        ///  [my:30s] [sy:-16s] [ey:-13s]
        ///# )
        ///
        ///-------------------------------------------------------------------------------
        ///Notes:
        ///
        ///DST - Time is in &apos;Daylight Savi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TplMasaListPlain {
            get {
                return ResourceManager.GetString("TplMasaListPlain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## TEMPLATE for RTF format
        ///## MASA LIST screen
        ///##
        ///{\rtf1\ansi\ansicpg1252\deff2\deflang1033{\fonttbl{\f0\fswiss\fcharset0 Lucida Console;}
        ///{\f1\fswiss\fcharset0 Arial;}{\f2\froman\fprq2\fcharset0 Book Antiqua;}}
        ///{\colortbl ;\red0\green0\blue0;\red16\green16\blue16;\red32\green32\blue32;\red48\green48\blue48;\red64\green64\blue64;
        ///\red80\green80\blue80;\red96\green96\blue96;\red112\green112\blue112;\red128\green128\blue128;\red143\green143\blue143;
        ///\red159\green159\blue159;\red175\green175\blue175;\re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TplMasaListRtf {
            get {
                return ResourceManager.GetString("TplMasaListRtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xml&gt;
        ///    &lt;body type=&quot;Masa List&quot;&gt;
        ///        &lt;location&gt;[location.fullName]&lt;/location&gt;
        ///        &lt;items&gt;
        ///# (foreach item : mlist.items
        ///	        &lt;masa&gt;
        ///				&lt;name&gt;[item.masaName]&lt;/name&gt;
        ///				&lt;year&gt;[item.year]&lt;/year&gt;
        ///				&lt;startDate&gt;[item.startDate.shortDate]&lt;/startDate&gt;
        ///				&lt;endDate&gt;[item.endDate.shortDate]&lt;/endDate&gt;
        ///			&lt;/masa&gt;
        ///# )
        ///		&lt;/items&gt;
        ///	&lt;/body&gt;
        ///&lt;/xml&gt;.
        /// </summary>
        internal static string TplMasaListXml {
            get {
                return ResourceManager.GetString("TplMasaListXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title,RATED EVENTS
        ///Range,From [events.startDate.shortDate] to [events.endDate.shortDate]
        ///Location,[location.fullName]
        ///#
        ///# (set prevDay -1)
        ///# (foreach ri : events.intervals
        ///#
        ///Interval;[ri.startTime.standardDateString]T[ri.startTime.standardTimeString];[ri.endTime.shortTime];[ri.title:40m];+[ri.ratingPos];[ri.ratingNeg]
        ///#   (set notes ri.notes)
        ///#   (if (!= notes.count 0) then
        ///#      (foreach s : notes
        ///Note;[ri.startTime.standardDateString]T[ri.startTime.standardTimeString];[s]
        ///#      )
        ///#    )
        ///#  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TplRatedCsv {
            get {
                return ResourceManager.GetString("TplRatedCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;&lt;title&gt;Rated Events&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;h1&gt;RATED EVENTS&lt;/h1&gt;
        ///&lt;h4&gt;From [events.startDate.shortDate] to [events.endDate.shortDate]&lt;br&gt;
        ///[location.fullName]&lt;/h4&gt;
        ///
        ///# (set prevDay -1)
        ///# (foreach ri : events.intervals
        ///#   (if (!= prevDay ri.startTime.day) then
        ///
        ///&lt;h3&gt; === [ri.startTime.shortDate:-12s] - [ri.startTime.dayOfWeekName] ======== &lt;/h3&gt;
        ///
        ///#   )
        ///#
        ///&lt;p&gt;&amp;nbsp;&amp;nbsp;      [ri.startTime.shortTime] - [ri.endTime.shortTime]  [ri.title:40m]  +[ri.ratingPos]  [ri.ratingNeg]&lt;/p&gt;
        ///#   ( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TplRatedHtml {
            get {
                return ResourceManager.GetString("TplRatedHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RATED EVENTS
        ///From [events.startDate.shortDate] to [events.endDate.shortDate]
        ///[location.fullName]
        ///
        ///# (set prevDay -1)
        ///# (foreach ri : events.intervals
        ///#   (if (!= prevDay ri.startTime.day) then
        ///
        ///=== [ri.startTime.shortDate:-12s] - [ri.startTime.dayOfWeekName] ========
        ///
        ///#   )
        ///#
        ///   [ri.startTime.shortTime] - [ri.endTime.shortTime]  [ri.title:40m]  +[ri.ratingPos]  [ri.ratingNeg]
        ///#   (set notes ri.notes)
        ///#   (if (!= notes.count 0) then
        ///#      (foreach s : notes
        ///                 [s]
        ///#      )
        ///#  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TplRatedPlain {
            get {
                return ResourceManager.GetString("TplRatedPlain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff2\deflang1033{\fonttbl{\f0\fswiss\fcharset0 Lucida Console;}
        ///{\f1\fswiss\fcharset0 Arial;}{\f2\froman\fprq2\fcharset0 Book Antiqua;}}
        ///{\colortbl ;\red0\green0\blue0;\red16\green16\blue16;\red32\green32\blue32;\red48\green48\blue48;\red64\green64\blue64;
        ///\red80\green80\blue80;\red96\green96\blue96;\red112\green112\blue112;\red128\green128\blue128;\red143\green143\blue143;
        ///\red159\green159\blue159;\red175\green175\blue175;\red191\green191\blue191;\red207\green207\blue207;\red22 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TplRatedRtf {
            get {
                return ResourceManager.GetString("TplRatedRtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RatedEvents&gt;
        ///  &lt;StartTime&gt;[events.startDate.shortDate]&lt;/StartTime&gt;
        ///  &lt;EndTime&gt;[events.endDate.shortDate]&lt;/EndTime&gt;
        ///  &lt;Location&gt;[location.fullName]&lt;/Location&gt;
        ///
        ///# (set prevDay -1)
        ///# (foreach ri in Intervals
        ///#     (if (!= prevDay ri.startTime.day) then
        ///#         (if (!= prevDay -1) then
        ///  &lt;/Day&gt;
        ///#         )
        ///  &lt;Day Date=&quot;[ri.startTime.shortDate]&quot; DayOfWeek=&quot;[ri.startTime.dayOfWeekName]&quot;&gt;
        ///#     )
        ///    &lt;Interval Start=&quot;[ri.startTime.shortTime]&quot; End=&quot;[ri.endTime.shortTime]&quot;
        ///	          Title=&quot;[ri.titl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TplRatedXml {
            get {
                return ResourceManager.GetString("TplRatedXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## TEMPLATE for TODAY screen
        ///## format PLAIN text
        ///##
        ///## comment is with two starting ##
        ///## setting of parsing characters for printed texts
        ///## these parsing constants are used for lines without preceding #
        ///##
        ///## these are examples
        ///##
        ///##   (set markupStart &apos;{ )
        ///##   (set markupEnd   &apos;} )
        ///##   (set escapeChar  &apos;\ )
        ///##
        ///
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;&lt;/title&gt;
        ///&lt;style&gt;
        ///&lt;!--\nbody {
        ///  font-family:Verdana;
        ///  font-size:9.5pt;
        ///}
        ///
        ///td.hed {
        ///  font-size:9.5pt;
        ///  font-weight:bold;
        ///  background:#aaaaaa;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TplTodayHtml {
            get {
                return ResourceManager.GetString("TplTodayHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## TEMPLATE for TODAY screen
        ///## format PLAIN text
        ///##
        ///## comment is with two starting ##
        ///## setting of parsing characters for printed texts
        ///## these parsing constants are used for lines without preceding #
        ///##
        ///## these are examples
        ///##
        ///##   (set markupStart &apos;{ )
        ///##   (set markupEnd   &apos;} )
        ///##   (set escapeChar  &apos;\ )
        ///##
        ///
        ///[today.dateHumanName]
        ///[location.name] ([location.longitudeString], [location.latitudeString], Timezone: [location.timezoneName])
        ///
        ///\[[today.date.day] [today.date.monthAbbr] [toda [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TplTodayPlain {
            get {
                return ResourceManager.GetString("TplTodayPlain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## TEMPLATE for RTF format
        ///## TODAY screen
        ///##
        ///{\rtf1\ansi\ansicpg1252\deff2\deflang1033{\fonttbl{\f0\fswiss\fcharset0 Lucida Console;}
        ///{\f1\fswiss\fcharset0 Arial;}{\f2\froman\fprq2\fcharset0 Book Antiqua;}}
        ///{\colortbl ;\red0\green0\blue0;\red16\green16\blue16;\red32\green32\blue32;\red48\green48\blue48;\red64\green64\blue64;
        ///\red80\green80\blue80;\red96\green96\blue96;\red112\green112\blue112;\red128\green128\blue128;\red143\green143\blue143;
        ///\red159\green159\blue159;\red175\green175\blue175;\red191 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TplTodayRtf {
            get {
                return ResourceManager.GetString("TplTodayRtf", resourceCulture);
            }
        }
    }
}
